## ANTES DE REALIZAR UMA ANÁLISE DE VARIÂNCIA EM DELINEAMENTO INTEIRAMENTE AO ACASO É 
## NECESSÁRIO TESTAR AS PRESSUPOSIÇÕES

## TESTA A NORMALIDADE DOS ERROS
shapiro.test(X)
## EXEMPLO

## shapiro.test(AOVDados$residuals)
## DETALHE: EXECUTE UMA ANOVA ATRAVÉS DO COMANDO AOV. COM A VARIÁVEL RESÍDUO DO RESULTADO
## DO COMANDO AOV, EXECUTE O TESTE DE SHAPIRO

## TESTA A INDEPENDÊNCIA DOS ERROS. PARA O TESTE CARREGUE O PACOT CAR, QUE DEVE SER
## PREVIAMENTE INSTALADO
require(car)
dwt(lm(anova))

## TESTA A HOMOGENEIDADE DAS VARIÂNCIAS. TESTE DE BARTLETT
bartlett.test(AOVDados$residuals~fatores$Trat,data = dados transformados)