## ANTES DE REALIZAR UMA ANÁLISE DE VARIÂNCIA EM DELINEAMENTO INTEIRAMENTE AO ACASO É 
## NECESSÁRIO TESTAR AS PRESSUPOSIÇÕES

## TESTA A NORMALIDADE DOS ERROS
shapiro.test(X)

## UM OUTRO MEIO DE VERIFICAR A NORMALIDADE É ATRAVÉS DO QQPLOT. PODE SER FEITO DE DUAS FORMAS
##
## FORMA 1
qqp(rstandard(anova),"norm")

## FORMA 2
qq(anova.residuo, "norm")

## EXEMPLO DE SHAPIRO.TEST

## shapiro.test(AOVDados$residuals)
## DETALHE: EXECUTE UMA ANOVA ATRAVÉS DO COMANDO AOV. COM A VARIÁVEL RESÍDUO DO RESULTADO
## DO COMANDO AOV, EXECUTE O TESTE DE SHAPIRO

## TESTA A INDEPENDÊNCIA DOS ERROS. PARA O TESTE CARREGUE O PACOT CAR, QUE DEVE SER
## PREVIAMENTE INSTALADO
require(car)
dwt(lm(anova))

## TESTA A HOMOGENEIDADE DAS VARIÂNCIAS. TESTE DE BARTLETT
bartlett.test(AOVDados$residuals~fatores$Trat,data = dados transformados)
