## UTILIZANDO O TESTE TUKEY DENTRO DO PACOTE EXPDES.PT

## PARA UTILIZAR ESSE EXEMPLO, É NECESSÁRIO INSTALAR O PACOTE ExpDes.pt.

## CARREGANDO O PACOTE EXPDES.PT, DEVE PREVIAMENTE SER INSTALADO
require(ExpDes.pt)

## PARA ESSE EXEMPLO UTILIZEI O ARQUIVO EXEMPLO-DADOS.CSV, QUE ESTÁ DENTRO DA PASTA:
## ANOVA/DIC. CONFIGURE O COMANDO SETWD PARA O CAMINHO QUE ESTÁ NO SEU COMPUTADOR.
##setwd("Endereço de onde está o arquivo Exemplo-dados.csv")

## LENDO O ARQUIVO DE DADOS E INFORMANDO QUE TEM CABEÇALHO E QUE O SEPARADORES SÃO; E O . É 
## O DECIMAL.
ob_dados <-read.csv("Exemplo-dados.csv", header = TRUE, sep=";",dec=".")

## CONFIGURA OS DADOS PARA TER UMA ESTRUTURA INTERNA DE OBJETO R. OU SEJA, OS CAMPOS
## TORNAM-SE OBJETOS.
str(ob_dados)

## TRANSFORMA OS DADOS EM DADOS, IMPORTANTE PARA NÚMEROS SEREM ENTENDIDOS COMO NÚMEROS
## E NÃO COMO STRINGS
ob_fatores<-transform(ob_dados, Trat=factor(TRAT), Rep=factor(REP));

## COMANDO DIC, PERTENCE AO PACOTE EXPDES. NOTE QUE JÁ SAI NA SEQUÊNCIA O TESTE SCOTTKNOTT
dic(trat=ob_fatores$TRAT, resp=ob_fatores$VALOR, quali = TRUE, mcomp = "tukey", nl = FALSE,
      hvar='bartlett', sigT = 0.05, sigF = 0.05)
  
