
## TESTE DE TUKEY

## PRIMEIRAMENTE DEVE-SE REALIZAR A ANÁLISE DE VARIÂNCIA COM O EFEITO DE TRATAMENTO FIXO.
## No EXEMPLO UTILIZOU O OBJETO ANOVA, ESTE RECEBEU OS DADOS DO COMANDO AOV.
TukeyHSD(anova)
